### List Products

GET http://localhost:3001/

###

GET http://localhost:3001/produto

###

GET http://localhost:3001/produto/2

###

POST http://localhost:3001/produto HTTP/1.1
content-type: application/json

{
    "id_tiny": 8468,
    "sku": "5646846846",
    "descricao": "Tênis Adidas",
    "ean": "6875455477554"
}

###

PATCH http://localhost:3001/produto/2 HTTP/1.1
content-type: application/json

{
    "tipo": "Gaveta"
}
###

DELETE http://localhost:3001/produto/4