services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: wms_db
    ports:
      - "5433:5432"  # Mapeia a porta 5432 do container para o host (localhost)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: