### List Products

GET http://localhost:3001/

###

GET http://localhost:3001/armazem

###

GET http://localhost:3001/armazem/1

###

POST http://localhost:3001/armazem HTTP/1.1
content-type: application/json

{
    "nome": "Dib Jorge",
    "endereco": "Av. Dib Jorge",
    "cidade": "Penápolis",
    "estado": "SP"
}

###

PATCH http://localhost:3001/armazem/1 HTTP/1.1
content-type: application/json

{
    "nome": "Dib Jorge"
}
###

DELETE http://localhost:3001/armazem/1