### List Products

GET http://localhost:3000/

###

GET http://localhost:3001/localizacao

###

GET http://localhost:3001/localizacao/1

###

POST http://localhost:3001/localizacao HTTP/1.1
content-type: application/json

{
    "status": "fechada",
    "nome": "WH-120",
    "altura": "10",
    "largura": 10,
    "tipo_localizacao_id": 1,
    "armazem_id": 1
}

###

PATCH http://localhost:3001/localizacao/1 HTTP/1.1
content-type: application/json

{
    "tipo_localizacao_id": 1
}

###

DELETE http://localhost:3000/localizacao/14
