### List Products

GET http://localhost:3000/

###

GET http://localhost:3000/localizacao

###

GET http://localhost:3000/localizacao/1

###

POST http://localhost:3000/localizacao HTTP/1.1
content-type: application/json

{
    "status": "fechada",
    "nome": "CH-10",
    "tipo_localizacao_id": 1,
    "armazem_id": 1
}

###

PATCH http://localhost:3000/localizacao/2 HTTP/1.1
content-type: application/json
{
    "tipo": "Gaveta"
}

###

DELETE http://localhost:3000/localizacao/14
