### List Products

GET http://localhost:3000/

###

GET http://localhost:3001/item-movimentacao

###

GET http://localhost:3001/item-movimentacao/1

###

POST http://localhost:3001/item-movimentacao HTTP/1.1
content-type: application/json

{
    "produto_id": 1,
    "quantidade": 10,
}

###

PATCH http://localhost:3001/item-movimentacao/1 HTTP/1.1
content-type: application/json

{
    "tipo_movimentacao_id": 1
}

###

DELETE http://localhost:3001/item-movimentacao/1
