### List Products

GET http://localhost:3000/

###

GET http://localhost:3001/item-auditoria

###

GET http://localhost:3001/item-auditoria/1

###

POST http://localhost:3001/item-auditoria HTTP/1.1
content-type: application/json

{
    "conclusao": "foi encontrado o produto faltando",
    "quantidades_sistema": 10,
    "quantidades_fisico": 8,
    "motivo_diferenca": "produto a menos",
    "acao_corretiva": "foi adicionado mais dois produtos no estoque",
    "estoque_anterior": 8,
    "estoque_novo": 10,
    "auditoria_id": 1
}

###

PATCH http://localhost:3001/item-auditoria/1 HTTP/1.1
content-type: application/json

{
    "tipo_auditoria_id": 1
}

###

DELETE http://localhost:3001/item-auditoria/1
